services:

  air:
    container_name: air
    build:
      context: .
      dockerfile: build/Dockerfile.air
    working_dir: /app
    networks:
      - web_app
    ports:
      - "8080:8080"
    environment:
      - LOAD_ENV_FILE=true
    healthcheck:
      test: curl -fsS localhost:8080/ping
    depends_on:
      - migrate
    volumes:
      - ./:/app/

  app:
    container_name: app
    build:
      context: .
      dockerfile: build/Dockerfile
    networks:
      - web_app
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    healthcheck:
      test: curl -fsS localhost:8080/ping
    depends_on:
      - migrate
    volumes:
      - ./web:/web

  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - web_app
    environment:
    - POSTGRES_USER=${CNOTES_DBUSER}
    - POSTGRES_PASSWORD=${CNOTES_DBPASS}
    - POSTGRES_DB=${CNOTES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${CNOTES_DBUSER} -d ${CNOTES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  migrate:
    container_name: migrate
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web_app
    volumes:
      - ./database/migrations/:/migrations
    command: ["-path", "/migrations/", "-database", "postgres://${CNOTES_DBUSER}:${CNOTES_DBPASS}@db:5432/${CNOTES_DB}?sslmode=disable", "up"]


networks:
  web_app:
    driver: bridge

volumes:
  dbdata: