name: Continuos Deployment - Main
on: 
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Up services
        run: |
          make up-app
